export class AssetInfo {
    item_id: string;
	category_id: string;
	location_id: string;
	item_name: string;
	item_description: string;
	item_assettype: string;
	item_location: string;
	item_manufacturer:string;
	item_brand: string;
	item_model:string;
	item_asset_number: string;
	item_qty: string;
	item_general_serialnumber: string;
	item_geenral_status: string;
	item_general_condition: string;
	item_general_checked_out_to: string;
	asset_owner: string;
	item_general_issue_date: string;
	item_general_due_date: string;
	item_general_notes: string;
	item_finance_accountno: string;
	item_finance_ponumber: string;
	item_finance_vendor: string;
	item_finance_purchased: string;
	item_finance_inservice: string;
	item_finance_purchaseprice: string;
	item_finance_currentvalue: string;
	item_finance_scrapvalue: string;
	item_finance_warrentyexpires: string;
	created_date_time: string;
	location_name: string;
	last_audit_date: string;
	asset_purchase_tax1: string;
	asset_purchase_tax2: string;
	asset_purchase_value: string;
	sub_category_id: string;
	locations_names: any[];
}